import {
  Activity,
  BatteryCharging,
  CarFront,
  FileCheck2,
  Gauge,
  Gift,
  Landmark,
  LandPlot,
  Leaf,
  Mountain,
  PlugZap,
  Receipt,
  Users,
  ShieldAlert,
  Sun,
  Thermometer,
  Truck,
  Warehouse,
  Zap,
} from "lucide-react";

/**
 * Alle Rechner & Tools – eine Quelle für Hub (/rechner), „Weitere Rechner“ auf
 * jeder Rechnerseite und das ItemList-Schema. Die Reihenfolge bestimmt, welche
 * sechs Tools unter „Weitere Rechner & Tools“ erscheinen (erste sechs ohne das
 * aktuelle und ohne den Konfigurator) – die wichtigsten Gewerbe-Tools daher zuerst.
 *
 * kategorie: wirtschaftlichkeit | speicher-netz | mobilitaet | standort-foerderung | esg | start
 */
export const KATEGORIEN = [
  { id: "wirtschaftlichkeit", titel: "Wirtschaftlichkeit", text: "Was bringt Photovoltaik auf Dach und Fläche – und wie wird sie finanziert?" },
  { id: "speicher-netz", titel: "Speicher & Netz", text: "Leistungspreis, Speicher, Energiegemeinschaft, Ausfallsicherheit und Börsenstrom." },
  { id: "mobilitaet", titel: "Mobilität", text: "Fuhrpark elektrifizieren und Ladepunkte mit Lastmanagement planen." },
  { id: "standort-foerderung", titel: "Standort & Förderung", text: "Schneelast und Naturgefahren prüfen, Förderungen und Steuervorteile finden." },
  { id: "esg", titel: "ESG & Klimabilanz", text: "Scope-2-Emissionen belegen – für Bericht, Bank und Kunden." },
];

export const TOOLS = [
  {
    id: "gewerbe-pv",
    href: "/rechner/gewerbe-pv",
    titel: "Gewerbe-PV-Rechner",
    kurz: "Was bringt Ihr Hallendach? Mit IRR, EAG & IFB",
    text: "Dachfläche, Standort und Schichtbetrieb eingeben – Eigenverbrauch, Amortisation, IRR, EAG-Zuschuss und Investitionsfreibetrag, stündlich simuliert.",
    icon: Warehouse,
    kategorie: "wirtschaftlichkeit",
    tag: "Neu",
  },
  {
    id: "solarrechner",
    href: "/solarrechner",
    titel: "Solarrechner",
    kurz: "Ertrag & Amortisation für Betrieb, Hof und Haus",
    text: "Für Gewerbe, Landwirtschaft und Privat: Anlagengröße, Verbrauch, Betriebszeiten und Dach eingeben – Eigenverbrauch, Ersparnis und Amortisation in Sekunden.",
    icon: Sun,
    kategorie: "wirtschaftlichkeit",
    tag: "Beliebt",
  },
  {
    id: "peak-shaving",
    href: "/rechner/peak-shaving",
    titel: "Peak-Shaving-Rechner",
    kurz: "Leistungspreis senken mit Gewerbespeicher",
    text: "Leistungspreise 2026 je Netzebene, Spitzentag mit und ohne Speicher, Speichergröße, PV-Eigenverbrauch und Amortisation – mit Ausblick auf 2027.",
    icon: Gauge,
    kategorie: "speicher-netz",
    tag: "Neu",
  },
  {
    id: "co2-esg",
    href: "/rechner/co2-esg",
    titel: "CO₂- & ESG-Rechner",
    kurz: "Scope 2 vorher/nachher – mit Berichtstext",
    text: "Scope-2-Emissionen standort- und marktbasiert vor und nach PV, Ökostrom und E-Flotte – mit kopierbarem Textbaustein für den Nachhaltigkeitsbericht.",
    icon: Leaf,
    kategorie: "esg",
    tag: "Neu",
  },
  {
    id: "energiegemeinschaft",
    href: "/rechner/energiegemeinschaft",
    titel: "Energiegemeinschafts-Rechner",
    kurz: "Geteilter Solarstrom für Gemeinde, Betriebe, Haushalte",
    text: "Geteilte Energie, Netzentgelt-Ersparnis 2026, Erlös gegenüber OeMAG-Marktpreis und fairer Win-win-Preis – mit Energiefluss-Diagramm.",
    icon: Users,
    kategorie: "speicher-netz",
    tag: "Neu",
  },
  {
    id: "e-flotte",
    href: "/rechner/e-flotte",
    titel: "E-Flotte-Rechner",
    kurz: "Firmenflotte auf Elektro: TCO, Steuern & CO₂",
    text: "Pkw, Transporter und Lkw: Gesamtkosten Verbrenner vs. Elektro mit Vorsteuer, Sachbezug, IFB, GO-Maut und Solarstrom – plus Ladepunkt-Empfehlung.",
    icon: Truck,
    kategorie: "mobilitaet",
    tag: "Neu",
  },
  {
    id: "freiflaeche-pacht",
    href: "/rechner/freiflaeche-pacht",
    titel: "Freiflächen- & Pacht-Rechner",
    kurz: "Für Grundeigentümer: Leistung, Ertrag, Pacht",
    text: "Wie viel Leistung passt auf Ihre Fläche – als Freifläche oder Agri-PV – und was bringt eine Verpachtung über die Laufzeit?",
    icon: LandPlot,
    kategorie: "wirtschaftlichkeit",
    tag: "Neu",
  },
  {
    id: "blackout",
    href: "/rechner/blackout",
    titel: "Blackout-Rechner",
    kurz: "Ausfallkosten, Notstrom & Dieselbedarf",
    text: "Was kostet ein Stromausfall? Ersatzstrom-Leistung, Speicher, Aggregat und Kraftstoff – plus Vorsorge-Checkliste.",
    icon: ShieldAlert,
    kategorie: "speicher-netz",
    tag: "Neu",
  },
  {
    id: "ladeinfrastruktur",
    href: "/rechner/ladeinfrastruktur",
    titel: "Ladeinfrastruktur-Planer",
    kurz: "Ladepunkte, Spitzenlast & Netzanschluss",
    text: "Tageslastkurve mit und ohne Lastmanagement, PV und Speicher – reicht Ihr Anschluss? Mit Richtkosten und Meldepflicht.",
    icon: PlugZap,
    kategorie: "mobilitaet",
    tag: "Neu",
  },
  {
    id: "stromspeicher",
    href: "/rechner/stromspeicher",
    titel: "Stromspeicher-Rechner",
    kurz: "Autarkie & wirtschaftliche Speichergröße",
    text: "Stündliche Jahressimulation: Wie viel Autarkie bringt welcher Speicher – und ab wann rechnet er sich?",
    icon: BatteryCharging,
    kategorie: "speicher-netz",
  },
  {
    id: "standort-check",
    href: "/standort-check",
    titel: "Standort-Check",
    kurz: "Schneelast, Wind, Hagel & Ertrag für Ihre Adresse",
    text: "Schneelast, Wind, Hagel & Ertrag für Ihre Adresse – mit eHORA und PVGIS.",
    icon: Mountain,
    kategorie: "standort-foerderung",
  },
  {
    id: "foerdercheck",
    href: "/foerdercheck",
    titel: "Förder-Check",
    kurz: "Zuschüsse & Steuervorteile in Österreich",
    text: "Welche Bundes- und Landesförderungen und welche steuerlichen Vorteile passen zu Ihrem Vorhaben?",
    icon: Gift,
    kategorie: "standort-foerderung",
  },
  {
    id: "ifb",
    href: "/forderungen/steuerlich#ifb-rechner",
    titel: "IFB-Rechner",
    kurz: "Investitionsfreibetrag 22 % bis Ende 2026",
    text: "Wie viel Steuer spart der Investitionsfreibetrag für PV, Speicher und Ladestationen – mit Zuschuss und Höchstbetrag?",
    icon: Receipt,
    kategorie: "standort-foerderung",
  },
  {
    id: "finanzierung",
    href: "/service/finanzierung#rechner",
    titel: "Finanzierungsrechner",
    kurz: "Annuität, Überschuss und IFB-Wirkung",
    text: "Investition, Eigenmittel und Beispielzins eingeben – Jahresrate, Überschuss aus der Anlage und Wirkung des Investitionsfreibetrags.",
    icon: Landmark,
    kategorie: "wirtschaftlichkeit",
  },
  {
    id: "waermepumpe",
    href: "/rechner/waermepumpe",
    titel: "Wärmepumpen-Rechner",
    kurz: "Heizkosten Gas/Öl vs. Wärmepumpe mit PV",
    text: "Vergleich der jährlichen Heizkosten und CO₂ gegenüber Gas und Heizöl – inklusive Solarstrom-Anteil je Monat.",
    icon: Thermometer,
    kategorie: "wirtschaftlichkeit",
  },
  {
    id: "wallbox",
    href: "/rechner/wallbox",
    titel: "E-Auto-Laderechner",
    kurz: "Tanken vs. Laden mit Netz- und Solarstrom",
    text: "Was kostet Ihr Kilometer mit Benzin, Diesel, Netzstrom oder Sonne vom eigenen Dach?",
    icon: CarFront,
    kategorie: "mobilitaet",
  },
  {
    id: "dynamisch",
    href: "/rechner/dynamischer-stromtarif",
    titel: "Dynamischer-Tarif-Rechner",
    kurz: "Mit Börsenpreisen der Gebotszone Österreich",
    text: "Festpreis oder Spotpreis-Tarif? Mit echten Day-Ahead-Preisen für Österreich und den günstigsten Ladefenstern.",
    icon: Zap,
    kategorie: "speicher-netz",
    tag: "Live",
  },
  {
    id: "energie-live",
    href: "/energie-live",
    titel: "Energie live",
    kurz: "Strompreis & Solarstrom in Echtzeit",
    text: "Börsenstrompreis, Solar- und Windeinspeisung – live aktualisiert.",
    icon: Activity,
    kategorie: "speicher-netz",
    tag: "Live",
  },
  {
    id: "angebot",
    href: "/angebot",
    titel: "Angebots-Konfigurator",
    kurz: "In 2 Minuten zum persönlichen Angebot",
    text: "Dach, Verbrauch und Wünsche angeben – wir melden uns mit einem konkreten Angebot.",
    icon: FileCheck2,
    kategorie: "start",
  },
];

export const toolById = (id) => TOOLS.find((t) => t.id === id);

/** Tools einer Kategorie in Listenreihenfolge */
export const toolsVon = (kategorie) => TOOLS.filter((t) => t.kategorie === kategorie);
